### ISSUE TITLE
Playstate.java should be PlayState.java

### ISSUE THREAD

**Issue by ghost** [sriharshachilakapati/RageCar#1]
Playstate.java should be PlayState.java to match up with the name of the class, as this can cause some issues to occur when building :stuck_out_tongue_winking_eye:

**Comment by sriharshachilakapati** [comment]
Wait, how did this happen? Worked fine in IntelliJ builds. Is Java class names case insensitive?

**Comment by sriharshachilakapati** [comment]
Something wrong with me committing to git, it was indeed named as PlayState.java in my file system. Fixed it now.
